#!/usr/bin/env bash
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/lucidsoftware/bazel.git}"
REPO_DIR="${REPO_DIR:-lucid-bazel}"
VERSION="${VERSION:-9.2.999}"
BAZEL_REF="${BAZEL_REF:-${VERSION}}"
BAZEL_REF_KIND="${BAZEL_REF_KIND:-tag}"
BAZELISK_VERSION="${BAZELISK_VERSION:-v1.29.0}"
BOOTSTRAP_BAZEL_VERSION="${BOOTSTRAP_BAZEL_VERSION:-9.2.0}"
ARTIFACT="${ARTIFACT:-bazel-${VERSION}-linux-arm64}"
UPLOAD="${UPLOAD:-0}"

if ! command -v docker >/dev/null 2>&1; then
  echo "docker is required" >&2
  exit 1
fi

if [[ ! -d "${REPO_DIR}/.git" ]]; then
  git clone "${REPO_URL}" "${REPO_DIR}"
fi

cd "${REPO_DIR}"
case "${BAZEL_REF_KIND}" in
  branch)
    if ! git ls-remote --exit-code --heads origin "${BAZEL_REF}" >/dev/null; then
      echo "ERROR: ${REPO_URL} has no branch named ${BAZEL_REF}" >&2
      echo "If you intended to build the release tag, rerun with:" >&2
      echo "  BAZEL_REF_KIND=tag ./build-jammy-arm-bazel.sh" >&2
      exit 1
    fi
    git fetch origin "refs/heads/${BAZEL_REF}:refs/remotes/origin/${BAZEL_REF}"
    git checkout -B "${BAZEL_REF}" "origin/${BAZEL_REF}"
    ;;
  tag)
    if ! git ls-remote --exit-code --tags origin "refs/tags/${BAZEL_REF}" >/dev/null; then
      echo "ERROR: ${REPO_URL} has no tag named ${BAZEL_REF}" >&2
      exit 1
    fi
    git fetch origin "refs/tags/${BAZEL_REF}:refs/tags/${BAZEL_REF}"
    git checkout --detach "${BAZEL_REF}"
    ;;
  *)
    echo "ERROR: BAZEL_REF_KIND must be 'branch' or 'tag', got '${BAZEL_REF_KIND}'" >&2
    exit 1
    ;;
esac

# Bazel includes the build timestamp in the stamped binary. Use the source
# commit time by default so rebuilding an architecture does not invalidate
# MODULE.bazel.lock files generated by another architecture from the same
# source revision. An existing release can supply its original timestamp.
SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-$(git show -s --format=%ct HEAD)}"

HOST_UID="$(id -u)"
HOST_GID="$(id -g)"

docker run --rm --platform linux/arm64 \
  -e HOST_UID="${HOST_UID}" \
  -e HOST_GID="${HOST_GID}" \
  -e VERSION="${VERSION}" \
  -e ARTIFACT="${ARTIFACT}" \
  -e BAZELISK_VERSION="${BAZELISK_VERSION}" \
  -e BOOTSTRAP_BAZEL_VERSION="${BOOTSTRAP_BAZEL_VERSION}" \
  -e SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH}" \
  -v "${PWD}:/workspace" \
  -w /workspace \
  ubuntu:22.04 bash -lc '
set -euxo pipefail
export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get install -y --no-install-recommends \
  ca-certificates curl git openjdk-21-jdk-headless \
  build-essential zip unzip python3 file binutils

curl -fsSL "https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK_VERSION}/bazelisk-linux-arm64" \
  -o /usr/local/bin/bazelisk
chmod +x /usr/local/bin/bazelisk

if ! getent group "${HOST_GID}" >/dev/null; then
  groupadd -g "${HOST_GID}" builder
fi

if ! getent passwd "${HOST_UID}" >/dev/null; then
  useradd -m -u "${HOST_UID}" -g "${HOST_GID}" -s /bin/bash builder
fi

BUILDER_USER="$(getent passwd "${HOST_UID}" | cut -d: -f1)"
HOME_DIR="$(getent passwd "${HOST_UID}" | cut -d: -f6)"
mkdir -p "${HOME_DIR}" /tmp/bazel-output
chown -R "${HOST_UID}:${HOST_GID}" "${HOME_DIR}" /tmp/bazel-output

runuser -u "${BUILDER_USER}" -- bash -lc "
  set -euxo pipefail
  cd /workspace
  git config --global --add safe.directory /workspace
  SOURCE_DATE_EPOCH=\"${SOURCE_DATE_EPOCH}\" \
    USE_BAZEL_VERSION=\"${BOOTSTRAP_BAZEL_VERSION}\" bazelisk \
    --ignore_all_rc_files \
    --output_user_root=/tmp/bazel-output \
    build -c opt --stamp --embed_label \"${VERSION}\" \
    --enable_platform_specific_config \
    --check_direct_dependencies=error \
    --experimental_downloader_config=bazel_downloader.cfg \
    --cxxopt=-std=c++17 \
    --host_cxxopt=-std=c++17 \
    --per_file_copt=external/.*@-w \
    --host_per_file_copt=external/.*@-w \
    --java_runtime_version=21 \
    --java_language_version=21 \
    --tool_java_runtime_version=21 \
    --tool_java_language_version=21 \
    --workspace_status_command=scripts/ci/build_status_command.sh \
    //src:bazel
  cp bazel-bin/src/bazel \"./${ARTIFACT}\"
"
'

docker run --rm --platform linux/arm64 \
  -e VERSION="${VERSION}" \
  -v "${PWD}:/workspace" \
  -w /workspace \
  ubuntu:22.04 bash -lc '
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive
apt-get update >/dev/null
apt-get install -y --no-install-recommends binutils file libc6 libstdc++6 unzip >/dev/null

embedded_label="$(unzip -p "'"${ARTIFACT}"'" build-label.txt)"
if [[ "${embedded_label}" != "${VERSION}" ]]; then
  echo "ERROR: embedded build label is ${embedded_label}, expected ${VERSION}" >&2
  exit 1
fi

release="$("./'"${ARTIFACT}"'" --batch --output_user_root=/tmp/bazel-validation info release)"
if [[ "${release}" != "release ${VERSION}" ]]; then
  echo "ERROR: artifact reports ${release}, expected release ${VERSION}" >&2
  exit 1
fi

file "'"${ARTIFACT}"'"
ldd "'"${ARTIFACT}"'"

echo
echo "Embedded build label: ${embedded_label}"
echo "Reported release: ${release}"

echo
echo "Version requirements from readelf:"
readelf --version-info "'"${ARTIFACT}"'" | grep -E "GLIBC|GLIBCXX" | sort -Vu

echo
echo "Version strings:"
strings "'"${ARTIFACT}"'" | grep -Eo "GLIBC_[0-9.]+|GLIBCXX_[0-9.]+" | sort -Vu

if strings "'"${ARTIFACT}"'" | grep -Eq "GLIBC_2\.38|GLIBCXX_3\.4\.32"; then
  echo "ERROR: artifact still requires GLIBC_2.38 or GLIBCXX_3.4.32" >&2
  exit 1
fi
'

echo
echo "Built and validated: ${PWD}/${ARTIFACT}"
echo "Expected release URL after upload:"
echo "https://github.com/lucidsoftware/bazel/releases/download/${VERSION}/${ARTIFACT}"

if [[ "${UPLOAD}" == "1" ]]; then
  if ! command -v gh >/dev/null 2>&1; then
    echo "gh is required for UPLOAD=1" >&2
    exit 1
  fi

  gh release upload "${VERSION}" "${ARTIFACT}" \
    --repo lucidsoftware/bazel \
    --clobber
fi
