#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_URL="${REPO_URL:-https://github.com/lucidsoftware/bazel.git}"
REPO_DIR="${REPO_DIR:-lucid-bazel}"
VERSION="${VERSION:-9.2.999}"
BAZEL_REF="${BAZEL_REF:-${VERSION}}"
EXPECTED_COMMIT="${EXPECTED_COMMIT:-7a93b11a481eb44362c5096d2307192c020ff192}"
BAZELISK_VERSION="${BAZELISK_VERSION:-v1.29.0}"
BAZELISK_SHA256="${BAZELISK_SHA256:-e20e8b0f4f240091b7a55bf17b9398bd4f40ee70ae0208dff95dd4c445fb4010}"
BOOTSTRAP_BAZEL_VERSION="${BOOTSTRAP_BAZEL_VERSION:-9.2.0}"
ARTIFACT="${ARTIFACT:-bazel-${VERSION}-linux-arm64}"
UPLOAD="${UPLOAD:-0}"

if [[ "${UPLOAD}" != "0" ]]; then
  echo "ERROR: build and upload are intentionally separate; run the reviewed gh release upload command after backup" >&2
  exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "docker is required" >&2
  exit 1
fi

container_arch="$(docker run --rm --platform linux/arm64 ubuntu:22.04 uname -m)"
if [[ "${container_arch}" != "aarch64" ]]; then
  echo "ERROR: Ubuntu 22.04 ARM64 container reported ${container_arch}, expected aarch64" >&2
  exit 1
fi
echo "Host architecture: $(uname -m)"
echo "Container architecture: ${container_arch}"

if [[ ! -d "${REPO_DIR}/.git" ]]; then
  git clone "${REPO_URL}" "${REPO_DIR}"
fi

cd "${REPO_DIR}"
if [[ -n "$(git status --porcelain)" ]]; then
  echo "ERROR: ${PWD} is not clean; use a fresh scratch directory" >&2
  exit 1
fi

remote_commit="$(git ls-remote --exit-code --tags origin "refs/tags/${BAZEL_REF}" | awk "NR == 1 {print \$1}")"
if [[ "${remote_commit}" != "${EXPECTED_COMMIT}" ]]; then
  echo "ERROR: tag ${BAZEL_REF} resolves to ${remote_commit}, expected ${EXPECTED_COMMIT}" >&2
  exit 1
fi
git fetch origin "refs/tags/${BAZEL_REF}:refs/tags/${BAZEL_REF}"
git checkout --detach "${BAZEL_REF}"

actual_commit="$(git rev-parse HEAD)"
if [[ "${actual_commit}" != "${EXPECTED_COMMIT}" ]]; then
  echo "ERROR: checked out ${actual_commit}, expected ${EXPECTED_COMMIT}" >&2
  exit 1
fi

# Bazel includes the build timestamp in the stamped binary. Use the source
# commit time by default so rebuilding an architecture does not invalidate
# MODULE.bazel.lock files generated by another architecture from the same
# source revision. An existing release can supply its original timestamp.
SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-$(git show -s --format=%ct HEAD)}"

HOST_UID="$(id -u)"
HOST_GID="$(id -g)"

docker run --rm --platform linux/arm64 \
  -e HOST_UID="${HOST_UID}" \
  -e HOST_GID="${HOST_GID}" \
  -e VERSION="${VERSION}" \
  -e ARTIFACT="${ARTIFACT}" \
  -e BAZELISK_VERSION="${BAZELISK_VERSION}" \
  -e BAZELISK_SHA256="${BAZELISK_SHA256}" \
  -e BOOTSTRAP_BAZEL_VERSION="${BOOTSTRAP_BAZEL_VERSION}" \
  -e SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH}" \
  -v "${PWD}:/workspace" \
  -w /workspace \
  ubuntu:22.04 bash -lc '
set -euxo pipefail
export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get install -y --no-install-recommends \
  ca-certificates curl git openjdk-21-jdk-headless \
  build-essential zip unzip python3 file binutils

curl -fsSL "https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK_VERSION}/bazelisk-linux-arm64" \
  -o /usr/local/bin/bazelisk
echo "${BAZELISK_SHA256}  /usr/local/bin/bazelisk" | sha256sum --check --strict
chmod +x /usr/local/bin/bazelisk

if ! getent group "${HOST_GID}" >/dev/null; then
  groupadd -g "${HOST_GID}" builder
fi

if ! getent passwd "${HOST_UID}" >/dev/null; then
  useradd -m -u "${HOST_UID}" -g "${HOST_GID}" -s /bin/bash builder
fi

BUILDER_USER="$(getent passwd "${HOST_UID}" | cut -d: -f1)"
HOME_DIR="$(getent passwd "${HOST_UID}" | cut -d: -f6)"
mkdir -p "${HOME_DIR}" /tmp/bazel-output
chown -R "${HOST_UID}:${HOST_GID}" "${HOME_DIR}" /tmp/bazel-output

runuser -u "${BUILDER_USER}" -- bash -lc "
  set -euxo pipefail
  cd /workspace
  git config --global --add safe.directory /workspace
  SOURCE_DATE_EPOCH=\"${SOURCE_DATE_EPOCH}\" \
    USE_BAZEL_VERSION=\"${BOOTSTRAP_BAZEL_VERSION}\" bazelisk \
    --ignore_all_rc_files \
    --output_user_root=/tmp/bazel-output \
    build -c opt --stamp --embed_label \"${VERSION}\" \
    --enable_platform_specific_config \
    --check_direct_dependencies=error \
    --lockfile_mode=off \
    --downloader_config=bazel_downloader.cfg \
    --cxxopt=-std=c++17 \
    --host_cxxopt=-std=c++17 \
    --per_file_copt=external/.*@-w \
    --host_per_file_copt=external/.*@-w \
    --java_runtime_version=remotejdk_21 \
    --java_language_version=21 \
    --tool_java_runtime_version=remotejdk_21 \
    --tool_java_language_version=21 \
    --workspace_status_command=scripts/ci/build_status_command.sh \
    //src:bazel
  cp bazel-bin/src/bazel \"./${ARTIFACT}\"
"
'

EXPECTED_VERSION="${VERSION}" "${SCRIPT_DIR}/validate-jammy-arm-bazel.sh" "${PWD}/${ARTIFACT}"

if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "ERROR: build changed tracked files in ${PWD}" >&2
  exit 1
fi

echo
echo "Built and validated: ${PWD}/${ARTIFACT}"
echo "Expected release URL after upload:"
echo "https://github.com/lucidsoftware/bazel/releases/download/${VERSION}/${ARTIFACT}"
